import numpy as np
import math
import scipy.stats as st
from matplotlib import pyplot as plt

n, days = 1000, 100
wolf_vec, wolf_S = [], []
fox_vec, fox_S = [], []
for i in range(n):
    nif_nif = np.random.normal(60, 100, days)
    naf_naf = np.random.normal(70, 100, days)
    nuf_nuf = np.random.normal(80, 100, days)
    mu_nif, mu_naf, mu_nuf = st.norm.fit(nif_nif), st.norm.fit(naf_naf), st.norm.fit(nuf_nuf)
    
    S = math.pow(mu_nif[0] - 60, 2) + math.pow(mu_naf[0] - 70, 2) + math.pow(mu_nuf[0] - 80, 2)
    buf = [mu_nif[0], mu_naf[0], mu_nuf[0]]
    wolf_vec.append(buf)
    wolf_S.append(S)

    buf = np.array(buf)
    nm = np.linalg.norm(buf)
    buf *= 1-1/(nm*nm)
    S = math.pow(buf[0] - 60, 2) + math.pow(buf[1] - 70, 2) + math.pow(buf[2] - 80, 2)
    fox_vec.append(buf)
    fox_S.append(S)
fox_vec = np.array(fox_vec)
fox_S = np.array(fox_S)
wolf_vec = np.array(wolf_vec)
wolf_S = np.array(wolf_S)

plt.hist(np.transpose(wolf_vec)[0])
plt.plot([60, 60], [0, 300])
plt.title("Гистограмма оценок волка для ниф-нифа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()
plt.hist(np.transpose(wolf_vec)[1])
plt.plot([70, 70], [0, 300])
plt.title("Гистограмма оценок волка для наф-нафа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()
plt.hist(np.transpose(wolf_vec)[2])
plt.plot([80, 80], [0, 300])
plt.title("Гистограмма оценок волка для нуф-нуфа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()

plt.hist(np.transpose(fox_vec)[0])
plt.plot([60, 60], [0, 300])
plt.title("Гистограмма оценок лиса для ниф-нифа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()
plt.hist(np.transpose(fox_vec)[1])
plt.plot([70, 70], [0, 300])
plt.title("Гистограмма оценок лиса для наф-нафа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()
plt.hist(np.transpose(fox_vec)[2])
plt.plot([80, 80], [0, 300])
plt.title("Гистограмма оценок лиса для нуф-нуфа")
plt.xlabel("Количество выполнений")
plt.ylabel("Количество оценок")
plt.show()

plt.title("Гистограмма средней квадратичной ошибки волка")
plt.xlabel("Средняя кв. ошибка")
plt.ylabel("Количество оценок")
plt.hist(wolf_S)
plt.show()
plt.title("Гистограмма средней квадратичной ошибки лиса")
plt.xlabel("Средняя кв. ошибка")
plt.ylabel("Количество оценок")
plt.hist(fox_S)
plt.show()

plt.title("Диаграмма рассеяния волка")
plt.xlabel("Оценка ниф-нифа")
plt.ylabel("Оценка наф-нафа")
plt.scatter(wolf_vec.transpose()[0], wolf_vec.transpose()[1])
plt.show()
print("Коэффициент выборочной корреляции волка:")
print(np.corrcoef(wolf_vec.transpose()[0], wolf_vec.transpose()[1])[0][1])

plt.title("Диаграмма рассеяния лиса")
plt.xlabel("Оценка ниф-нифа")
plt.ylabel("Оценка наф-нафа")
plt.scatter(fox_vec.transpose()[0], fox_vec.transpose()[1])
plt.show()
print("Коэффициент выборочной корреляции лиса:")
print(np.corrcoef(fox_vec.transpose()[0], fox_vec.transpose()[1])[0][1])
